sudo: required

dist: trusty

language: true

services:
- postgresql

addons:
- postgresql: '9.4'

install: sudo bash install.sh

script:
- sudo bash build.sh

notifications:
  email:
  - daniel.j.dufour@gmail.com

#deploy:
#  provider: s3
#  access_key_id: AKIAIKYVD3MMO44ID6XA
#  secret_access_key:
#    secure: XqB4EfO8yfmtNRk/utOhAxsHxRBzwVGyZYgMdcrHcZtD4M/m7+3nK2oweda0YSrcHd1cNrxkhc9LGhKQtkJ5ilSO21mSl2cDxx6S0fyXkx7CuEm7cZ89C9SkyPtSRUC71qj6BVTJT9qFE5EZbvqQY8ryDMIHfqmTyCE0xVMdjZZaKhFcEWjr2PNBrJfQQDg7wiNqwkHf9+9oHL6/gag9LxbpLc74DQou9X2wlx5s4ygNILt3eZ5f662blFznhywrQbhgpNriGnGIF5PErhlJUU/xX5a7ZHdSDunZPnpRvDwtr9jOgIvtPqLSxXyRHIqoFb0yalZyeBOjFXB49TLIAd+D3JyTAG6bfv9aRbOdWhOxFWsuRMB89KJvgxSBrRf+A+RxzCFUKpoDa2yurxnTw5rOZ8ymmHkK2mtOXPGPsm8UOB6A0YlH0jgWr7mZMI8yNItWIjG9Uch98FkumPgApskj1dVDz9cDRHIWLtz8vkZfx9vofPOdH9Ymd6ZAqKVXeJkyIF4HD/1yJ5BqvsUM/0EK5VP7cErt3RQjxWGyQ/f+fXQJaSQGKQBHU847d84iFDP5zqpx/rpx1h+YH7alMtXkp+3qgH+ESgduhss+1njU6kQTMaKzZ0ikdakCDzYi891Ut9FtvNRWECj7B3/15/f5gzNRCtV5vk3UTuKjQAU=
#  bucket: firstdraftgis
#  on:
#    repo: DanielJDufour/firstdraft
