sudo: required

dist: trusty

language: True

# this makes sure postgresql service is running
services:
  - postgresql

addons:
  - postgresql: "9.4"

install: sudo bash install.sh

script:
  - sudo bash build.sh

notifications:
    email:
        - daniel.j.dufour@gmail.com
