sudo: required

dist: trusty

# this makes sure postgresql service is running
services:
  - postgresql

addons:
  - postgresql: "9.4"

language: python

python:
  - "2.7"

install: sudo bash install.sh

script:
  - sudo bash build.sh

notifications:
    email:
        - daniel.j.dufour@gmail.com
