sudo: required

dist: trusty

# this makes sure postgresql service is running
services:
  - postgresql

addons:
  - postgresql: "9.4"

language: python

python:
  - "2.7"

install:
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confnew" install apache2 apache2-dev apache2-mpm-prefork apt-file build-essential cmake curl libapache2-mod-wsgi libboost-all-dev libcgal-dev libgdal1-dev libgeos-dev libgmp3-dev libmpfr-dev libmpfr-doc libmpfr4 libmpfr4-dbg libproj-dev libpq-dev python-qgis python-virtualenv qgis vim zip libxslt1-dev
  - psql -U postgres -c "CREATE extension postgis"
  - psql -U postgres -c "CREATE extension postgis_topology"
  - psql -U postgres -c "CREATE extension fuzzystrmatch"
  - psql -U postgres -c 'CREATE database dbfd'
  - psql -U postgres -c 'CREATE user usrfd'
  - psql -U postgres -c 'ALTER DATABASE dbfd OWNER TO usrfd'
  - sudo useradd usrfd -m
  - sudo -u usrfd git clone http://github.com/danieljdufour/firstdraft.git /home/usrfd/firstdraft
  - sudo chown usrfd:usrfd /home/usrfd/firstdraft -R
  

script:
  - sudo bash build.sh

notifications:
    email:
        - daniel.j.dufour@gmail.com
